#
# NDSLabs cluster on OpenStack - HW Setup
#

- name: set facts from cache
  hosts: all 
  gather_facts: false
  tasks:
    - set_fact: ansible_host={{ logical_cluster_name }}-{{ inventory_hostname }}
    - set_fact: ansible_hostname={{ logical_cluster_name }}-{{ inventory_hostname }}
    - set_fact: ansible_ssh_host={{ ansible_default_ipv4.address }}
    - set_fact: ansible_ssh_private_key_file={{key_path}}/{{key_name}}.pem

##########################################################################################################################
# Now to kubernetes, back again after
##########################################################################################################################
- include: /usr/local/lib/kubernetes/contrib/ansible/cluster.yml
