#
# NDSLabs cluster on OpenStack - deploy kubernetes on systems
#
- name: setup ansible host vars
  hosts: all
  roles:
    - ansible_host_vars_setup

##########################################################################################################################
# Now to kubernetes, back again after to install system services
##########################################################################################################################
- include: /usr/local/lib/kubernetes/contrib/ansible/cluster.yml

- name: kube-system namespace
  hosts: masters[0]
  tasks:
    - shell: kubectl create namespace kube-system

- name: start DNS
  hosts: masters[0]
  roles:
    - cluster-dns

