#
# NDSLabs cluster - reset to base systems - uninstall kubernetes
#

- name: setup ansible host vars
  hosts: all
  roles:
    - ansible_host_vars_setup

- name: Clean master /tmp
  hosts: masters
  tasks:
    - command: rm -f /tmp/*

########################################################################################
# Unwind K8s 
########################################################################################
- include:  /usr/local/lib/kubernetes/contrib/ansible/playbooks/adhoc/uninstall.yml


