#
# NDSLabs cluster on OpenStack - deploy kubernetes on systems
#
- name: setup ansible host vars
  hosts: all
  roles:
    - ansible_host_vars_setup

##########################################################################################################################
# Now to kubernetes install
##########################################################################################################################
- include: /usr/local/lib/kubernetes/contrib/ansible/playbooks/deploy-cluster.yml

- name: kubectl | get from master
  hosts: masters
  run_once: true
  tasks:
    - local_action: shell scp -o StrictHostKeyChecking=no -p {{ logical_cluster_name }}-{{ inventory_hostname }}:/opt/bin/kubectl /usr/local/bin/kubectl

