#
# NDSLabs cluster - reset to base systems - uninstall kubernetes
#

- name: setup ansible host vars
  hosts: all
  roles:
    - ansible_host_vars_setup

- name: Clean master /tmp
  hosts: masters
  become: true
  tasks:
    - shell: rm -f /tmp/* || true 

########################################################################################
# Unwind K8s 
########################################################################################
- include:  /usr/local/lib/kubernetes/contrib/ansible/playbooks/adhoc/uninstall.yml

- name: Reinstall k8s uninstalled python bootstrap
  hosts: all
  become: true
  roles:
    - pre-ansible


