#
# NDSLabs cluster on OpenStack - deploy kubernetes on systems
#
- name: setup ansible host vars
  hosts: all
  roles:
    - ansible_host_vars_setup

##########################################################################################################################
# Now to kubernetes, back again after
##########################################################################################################################
- include: /usr/local/lib/kubernetes/contrib/ansible/cluster.yml
