#
# NDSLabs cluster on OpenStack - HW Setup
#

- name: prepend logical cluster name for all cluster resources
  hosts: all 
  gather_facts: false
  tasks:
    - set_fact:  ansible_host={{ logical_cluster_name }}-{{ inventory_hostname }}
    #- set_fact:  inventory_hostname={{ ansible_host }}

- name: Pre Checks
  hosts: cluster
  gather_facts: false
  roles: 
    - pre-checks

- name: OpenStack Key
  hosts: cluster
  gather_facts: false
  run_once: true
  roles: 
    - openstack-key

- name: OpenStack LoadBalancer Security Group
  hosts: publicip
  gather_facts: false
  roles: 
    - openstack-securitygroup-open

- name: NDSLabs OpenStack Cluster
  hosts: cluster
  gather_facts: false
  roles: 
    - openstack-system

- name: CoreOS Setup
  hosts: cluster
  gather_facts: false
  become: true
  roles:
    - pre-ansible

- name: NDSLabs environment setup
  hosts: cluster
  become: true
  roles:
    - cluster-addrs-etc-hosts

- name: CoreOS NDSLabs Preferences
  hosts: coreos
  roles:
    - coreos-ndslabs-devsystem

- name: OpenStack GLFS provision volume and attach
  hosts: glfs:&openstack
  roles: 
    - openstack-volume-attached
    - coreos-mount

- name: GLFS brick dir
  hosts: glfs
  become: true
  tasks:
    - file: path=/media/brick0/brick state=directory mode=0777

- name: CoreOS Mount GLFS
  hosts: glfs:&coreos
  roes: 
    - coreos-mount

- name: CoreOS Mount GLFS
  hosts: glfs:&coreos
  roles: 
    - coreos-mount

##########################################################################################################################
# Now to kubernetes, back again after
##########################################################################################################################
- include: /usr/local/lib/kubernetes/contrib/ansible/cluster.yml
 
##########################################################################################################################
# Clean up known K8's troubles
##########################################################################################################################

- name: stop and disable kube-addons
  hosts: masters
  become: true
  tasks:
    - service: name=kube-addons state=stopped enabled=false


##########################################################################################################################
# Now additional setup now that the cluster is running
##########################################################################################################################

- name: LoadBalancer public interface
  hosts: loadbal
  gather_facts: false
  connection: local
  tasks:
    - os_floating_ip: server="{{ inventory_hostname }}" 

- name: NDSLabs initial labels
  hosts: loadbal compute glfs
  roles:
    - ndslabs-k8-init-labels

- name: NDSLabs GLFS Global Cluster Filesystem Servers
  hosts: glfs
  #gather_facts: false
  roles:
    - k8-glfs-server-pods

- name: NDSLabs GLFS Cluster FileSystem Clients
  hosts: nodes
  roles:
    - k8-glfs-client-set

- name: NDSLabs Ingress Loadbalancer
  hosts: masters
  roles:
    - ndslabs-loadbalancer
