#
# NDSLabs cluster on OpenStack - HW Setup
#

- name: Pre Checks
  hosts: cluster
  gather_facts: false
  roles: 
    - pre-checks

- name: OpenStack Key
  hosts: cluster
  gather_facts: false
  run_once: true
  roles: 
    - openstack-key

- name: OpenStack LoadBalancer Security Group
  hosts: publicip
  gather_facts: false
  roles: 
    - openstack-securitygroup-open

- name: NDSLabs OpenStack Cluster
  hosts: cluster
  gather_facts: false
  roles: 
    - openstack-system

- name: CoreOS Setup
  hosts: cluster
  gather_facts: false
  become: true
  roles:
    - pre-ansible
    #- defunctzombie.coreos-bootstrap

- name: NDSLabs environment setup
  hosts: cluster
  become: true
  roles:
    - cluster-addrs-etc-hosts

- name: CoreOS NDSLabs Preferences
  hosts: coreos
  roles:
    - coreos-ndslabs-devsystem

- name: OpenStack GLFS provision volume and attach
  hosts: glfs:&openstack
  roles: 
    - openstack-glfs


- name: CoreOS Mount GLFS
  hosts: glfs:&coreos
  roles: 
    - coreos-mount

- name: CoreOS Mount GLFS
  hosts: glfs:&coreos
  roles: 
    - coreos-mount

##########################################################################################################################
# Now to kubernetes, back again after
##########################################################################################################################
- include: /usr/local/lib/kubernetes/contrib/ansible/cluster.yml

##########################################################################################################################
# Now additional setup now that the cluster is running
##########################################################################################################################

- name: NDSLabs initial labels
  hosts: all
  roles:
    - ndslabs-k8-init-labels

- name: NDSLabs Gluster Server
  hosts: glfs
  roles:
    - k8-glfs-server-pods

- name: NDSLabs Ingress Loadbalancer
  hosts: master
  roles:
    - ndslabs-loadbalancer
