#
# NDSLabs cluster on OpenStack - HW Setup
#

- name: prepend logical cluster name for all cluster resources
  hosts: all 
  gather_facts: false
  tasks:
    - set_fact: ansible_host={{ logical_cluster_name }}-{{ inventory_hostname }}
    - set_fact: ansible_ssh_host={{ ansible_default_ipv4.address }}
    - set_fact: ansible_ssh_private_key_file={{key_path}}/{{key_name}}.pem


- name: Clean master /tmp
  hosts: masters
  tasks:
    - command: rm -f /tmp/*

########################################################################################
# Unwinde K8s 
########################################################################################
- include:  /usr/local/lib/kubernetes/contrib/ansible/playbooks/adhoc/uninstall.yml


