#
# NDSLabs cluster on OpenStack - HW Setup
#
- name: OpenStack Key
  hosts: cluster
  
  run_once: true
  roles: 
    - openstack-key

- name: NDSLabs OpenStack Cluster
  hosts: cluster
  
  roles: 
    - openstack-system

##########################################################################################################################
# Now additional setup now that the cluster is running
##########################################################################################################################

- name: NDSLabs Gluster Server
  hosts: glfs
  roles:
    - k8-glfs-server-pods
