#
# Destroy all glfs state and data in the cluster
# All gluster clients and servers should be down
#
#  This is NON-RECOVERABLE and will DESTROY ALL DATA
#

- name: setup ansible host vars
  hosts: all
  roles:
    - ansible_host_vars_setup

- name: glfs server state directories
  hosts: glfs
  become: true
  tasks:
    - file: path="{{ item }}" state=absent
      with_items:
      - /var/lib/glusterd
      - /var/log/glusterfs
      - /etc/glusterfs
      - /media/brick0/brick
      - /var/lib/xfsdump
    - file: path="{{ item }}" state=directory
      with_items:
      - /var/lib/glusterd
      - /var/log/glusterfs
      - /etc/glusterfs
      - /media/brick0/brick
      - /var/lib/xfsdump

- name: glfs node state directories
  hosts: cluster
  become: true
  tasks:
  - shell: umount -f /var/glfs/global || true
  - file: path="/var/glfs" state=absent
  - file: path="/var/glfs" state=directory mode=0777


  


