
- name: deploy local cache yaml
  copy: src={{ item }} dest=/tmp/{{ item }}
  register: dreg
  with_items:
    - docker-cache-rc.yaml
    - docker-cache-svc.yaml
    - docker-cache-proxy-ds.yaml
    - config.yml

- name: deploy cache configmap with cache
  command: /opt/bin/kubectl apply -f /tmp/{{ item }}
  with_items:
    - config.yml
  when: dreg.changed

- name: deploy cache into kubernetes
  command: /opt/bin/kubectl apply -f /tmp/{{ item }}
  with_items:
    - docker-cache-rc.yaml
    - docker-cache-svc.yaml
    - docker-cache-proxy-ds.yaml
  when: dreg.changed
