---

- name: Security Group
  connection: local
  become: false
  os_security_group:
    state: present
    wait: yes
    name: k8s_loadbalancer
    description: security group k8s in-cluster sw load balancer

- name: Remove Security Group Rule - Wide Open IPv6
  connection: local
  become: false
  os_security_group_rule:
    security_group: k8s_loadbalancer
    protocol: tcp
    ethertype: IPv6
    remote_ip_prefix: ::/0
    state: absent

- name: Remove Security Group Rule - Wide Open IPv4
  connection: local
  become: false
  os_security_group_rule:
    security_group: k8s_loadbalancer
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0
    state: absent

- name: Add Security Group Rule - Port 80 IPv6
  connection: local
  become: false
  os_security_group_rule:
    security_group: k8s_loadbalancer
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    ethertype: IPv6
    remote_ip_prefix: ::/0
    state: present

- name: Add Security Group Rule - Port 80 IPv4
  connection: local
  become: false
  os_security_group_rule:
    security_group: k8s_loadbalancer
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
    state: present

- name: Add Security Group Rule - Port 443 IPv6
  connection: local
  become: false
  os_security_group_rule:
    security_group: k8s_loadbalancer
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    ethertype: IPv6
    remote_ip_prefix: ::/0
    state: present

- name: Add Security Group Rule - Port 443 IPv4
  connection: local
  become: false
  os_security_group_rule:
    security_group: k8s_loadbalancer
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
    state: present
