---
ansible_user: core
ansible_python_interpreter: /opt/bin/python
#ansible_python_interpreter: "PATH=/opt/bin:$PATH python"
#ansible_python_interpreter: "PATH=/home/core/bin:$PATH python"
is_coreos: True
