
    
- name: Cluster Addons| populate template
  template: src="{{ item }}.j2" dest="/tmp/{{ item }}"
  with_items:
    - kube-system-ingress.yaml
    
    
##########################################################################################################################
# Create ingress rules
##########################################################################################################################
- include: /usr/local/lib/ndslabs/ansible/roles/cluster-addons/tasks/init.yml
